from factory import usage


def test_parses_events_with_appended_footer():
    bodies = ['usage-event `{"event": "start", "run_id": "a", "at": "2026-10-04T08:03:00+00:00"}`',
              'usage-event `{"event": "end", "run_id": "a", "at": "2026-10-04T08:05:00+00:00", "tasks": 1}`\n\n'
              '---\n_Generated by [Claude Code](https://claude.ai/code)_',
              'unrelated comment', None]
    ev = usage.parse_comments(bodies)
    assert [e["event"] for e in ev] == ["start", "end"]
    assert usage.runs(ev)[0]["tasks_done"] == 1
