"""Results section of the README, built deterministically from the ledger and the paper account.

    python -m factory.readme --ledger ledger/ --readme README.md [--no-broker]

Rewrites only the text between the RESULTS_START and RESULTS_END markers, so the hand-written parts of
the file stay as they are. .github/workflows/readme.yml runs it daily into RESULTS.md on the `results`
branch (main only accepts PRs); a PR can refresh the snapshot in README.md. Needs no Claude.
"""
from __future__ import annotations

import argparse
import ast
import datetime as dt
import json
import os
import sys
from pathlib import Path

from factory.config import ROOT

RESULTS_START = "<!-- results:start (generated by factory/readme.py; edits here are overwritten) -->"
RESULTS_END = "<!-- results:end -->"
BASELINES = {"equal_weight_buy_hold", "sma_trend", "cross_sectional_momentum", "short_term_reversal",
             "opening_range_breakout"}


def _load(path: Path) -> dict | None:
    try:
        return json.loads(path.read_text())
    except (OSError, ValueError):
        return None


def _num(x, fmt: str) -> str:
    return format(float(x), fmt) if isinstance(x, (int, float)) else "n/a"


def executions(ledger: Path) -> list[dict]:
    runs = [r for r in (_load(f) for f in sorted((ledger / "executions").glob("*.json"))) if r]
    return sorted(runs, key=lambda r: str(r.get("started_at")))


def latest_experiments(ledger: Path) -> dict[str, dict]:
    """Latest real-data evaluation of each strategy, by name."""
    out: dict[str, dict] = {}
    for f in sorted((ledger / "experiments").glob("*.json")):
        r = _load(f)
        if not r or "strategy" not in r or "metrics" not in r:
            continue
        if str((r.get("data") or {}).get("source", "")).startswith("synthetic"):
            continue
        name = r["strategy"]["name"]
        if name not in out or str(r.get("evaluated_at")) > str(out[name].get("evaluated_at")):
            out[name] = r
    return out


def methodology(ref: str) -> str:
    """First paragraph of the champion file's docstring, joined onto one line."""
    try:
        doc = ast.get_docstring(ast.parse((ROOT / ref).read_text())) or ""
    except (OSError, SyntaxError):
        return ""
    return " ".join(doc.split("\n\n")[0].split())


def trading_section(runs: list[dict], broker) -> list[str]:
    submitted = [o for r in runs for o in (r.get("submitted") or [])]
    days = sorted({str(r.get("started_at"))[:10] for r in runs if r.get("submitted")})
    lines = ["### Paper trading",
             f"- Orders sent to the paper accounts so far (all funds): **{len(submitted)}** on {len(days)} trading day(s); "
             f"{len(runs)} executor run(s) recorded."]
    if runs:
        last = runs[-1]
        lines.append(f"- Last executor run {str(last.get('started_at'))[:16].replace('T', ' ')} UTC: {last.get('status')}")
    if not submitted:
        lines.append("- No paper trades yet. Earlier runs were dry runs or stopped by the fail-closed checks; "
                     "the scheduled executor trades weekdays at 15:00 UTC.")
    if broker is None:
        return lines + ["- Paper account not checked in this build."]
    lines.append("- Fund 1 account in detail:")
    try:
        acct = broker.account()
        equity = float(acct["equity"])
        last_eq = float(acct.get("last_equity") or equity)
        hist = [float(x) for x in (broker.portfolio_history().get("equity") or []) if x]
        start = hist[0] if hist else equity
        positions = broker.positions() or []
    except Exception as e:  # the README must still update
        return lines + [f"- Could not read the paper account: {type(e).__name__}"]
    lines += [
        f"- Equity **${equity:,.0f}**. Last trading day {equity - last_eq:+,.0f} ({(equity / last_eq - 1) if last_eq else 0:+.2%}); "
        f"overall {equity - start:+,.0f} ({(equity / start - 1) if start else 0:+.2%}) since ${start:,.0f}.",
        f"- Cash ${float(acct.get('cash', 0)):,.0f}; {len(positions)} open position(s).",
    ]
    if positions:
        lines += ["", "| Holding | Shares | Market value | Unrealised P&L |", "|---|---|---|---|"]
        for p in sorted(positions, key=lambda p: -abs(float(p.get("market_value") or 0))):
            lines.append(f"| {p.get('symbol')} | {p.get('qty')} | ${float(p.get('market_value') or 0):,.0f} | "
                         f"{float(p.get('unrealized_pl') or 0):+,.0f} |")
    return lines


def _account_figures(broker) -> dict:
    acct = broker.account()
    equity = float(acct["equity"])
    last_eq = float(acct.get("last_equity") or equity)
    hist = [float(x) for x in (broker.portfolio_history().get("equity") or []) if x]
    return {"equity": equity, "day": equity - last_eq, "day_pct": equity / last_eq - 1 if last_eq else 0.0,
            "start": hist[0] if hist else equity}


def fund_section(runs: list[dict], brokers: dict | None) -> list[str]:
    """Leaderboard of the paper funds (state/funds.yaml), best total return first; unfunded funds last."""
    from factory import funds
    try:
        fs = funds.load()
    except Exception as e:
        return ["### Fund leaderboard", f"- Could not read state/funds.yaml: {type(e).__name__}"]
    trades: dict[int, int] = {}
    for r in runs:
        n = int(r.get("fund") or 1)   # runs from before the funds existed were the original account, fund 1
        trades[n] = trades.get(n, 0) + len(r.get("submitted") or [])
    rows = []
    for f in fs:
        try:
            strat = f"`{funds.strategy(f)['name']}`" + (" (champion)" if f.strategy == "champion" else "")
        except Exception:
            strat = "invalid assignment"
        if brokers is None:
            rows.append((0, f.number, f"| {f.number} | {f.label} | {strat} | not checked in this build | | | {trades.get(f.number, 0)} |"))
            continue
        b = brokers.get(f.number)
        if b is None:
            rows.append((2, 0.0, f"| {f.number} | {f.label} | {strat} | not funded yet | | | {trades.get(f.number, 0)} |"))
            continue
        try:
            a = _account_figures(b)
        except Exception as e:
            rows.append((1, 0.0, f"| {f.number} | {f.label} | {strat} | unavailable ({type(e).__name__}) | | | "
                                 f"{trades.get(f.number, 0)} |"))
            continue
        total = a["equity"] / a["start"] - 1 if a["start"] else 0.0
        rows.append((0, -total, f"| {f.number} | {f.label} | {strat} | ${a['equity']:,.0f} | {a['day']:+,.0f} ({a['day_pct']:+.2%}) | "
                                f"{a['equity'] - a['start']:+,.0f} ({total:+.2%}) | {trades.get(f.number, 0)} |"))
    return ["### Fund leaderboard",
            "Each fund is its own Alpaca paper account running the strategy in `state/funds.yaml`. Names are just for fun; "
            "strategies move between funds whenever research suggests. Total P&L is since the account's first recorded equity.",
            "", "| # | Fund | Strategy now | Equity | Last day | Total P&L | Trades |", "|---|---|---|---|---|---|---|"
            ] + [r[2] for r in sorted(rows, key=lambda r: r[:2])]


def _verdict(r: dict) -> str:
    if r.get("promote"):
        return "promoted"
    if r.get("passed_gates"):
        return "passed gates"
    failed = [g["gate"] for g in r.get("gates") or [] if not g.get("passed") and not g.get("promotion_only")]
    return "rejected" + (f" ({', '.join(failed)})" if failed else "")


def _row(name: str, r: dict) -> str:
    m = r["metrics"]
    i, v, h = m.get("in_sample") or {}, m.get("validation") or {}, m.get("holdout") or {}
    return (f"| `{name}` | {r['strategy'].get('timeframe')} | {_verdict(r)} | {_num(i.get('sharpe'), '.2f')} | "
            f"{_num(v.get('sharpe'), '.2f')} | ~{_num(h.get('sharpe'), '.1f')} | {_num(v.get('max_drawdown'), '.0%')} | "
            f"{_num(v.get('annual_turnover'), '.1f')} |")


def _periods() -> str:
    from factory import config
    try:
        per = config.evaluation()["periods"]
        return ", ".join(f"{tf} {p['validation']['start'][:7]} to {p['validation']['end'][:7]}" for tf, p in per.items())
    except Exception:
        return "see protected/evaluation.yaml"


def research_section(ledger: Path, champ: dict) -> list[str]:
    latest = latest_experiments(ledger)
    runs = [r for r in (_load(f) for f in (ledger / "experiments").glob("*.json")) if r and "strategy" in r]
    if (rec := _load(ledger / "experiments" / f"{champ.get('experiment_id')}.json")) and "metrics" in rec:
        latest[champ["name"]] = rec   # the record the champion was promoted on, not a later re-run
    cands = {n: r for n, r in latest.items() if n not in BASELINES}
    passed = [n for n, r in cands.items() if r.get("passed_gates")]
    promoted = sorted({r["strategy"]["name"] for r in runs if r.get("promote")})
    lines = ["### Research",
             f"- {len(cands)} candidate strategies tested on real data ({len(runs)} evaluations in total, re-runs included): "
             f"{len(passed)} passed every gate, {len(cands) - len(passed)} rejected, "
             f"{len(promoted)} promoted ({', '.join(f'`{p}`' for p in promoted) or 'none'}).",
             "- Sharpe ratios are after costs and slippage. Validation periods: " + _periods() + ". The holdout "
             "(unseen) figure is rounded on purpose so research cannot tune to it.",
             "", "| Strategy | Bars | Verdict | In-sample Sharpe | Validation Sharpe | Holdout Sharpe | Validation max DD | Turnover/yr |",
             "|---|---|---|---|---|---|---|---|"]
    order = sorted(cands, key=lambda n: (n != champ.get("name"), not cands[n].get("passed_gates"),
                                         -float((cands[n]["metrics"].get("validation") or {}).get("sharpe") or -99)))
    lines += [_row(n, cands[n]) for n in order]
    ref = cands.get(champ.get("name")) or next(iter(latest.values()), None)
    if ref:
        v = ref.get("benchmark", {}).get("metrics", {}).get("validation", {})
        bl = ref.get("baselines") or {}
        lines += ["", "Fixed benchmarks on the same validation period: SPY Sharpe "
                  f"{_num(v.get('sharpe'), '.2f')}; " + "; ".join(
                      f"`{k}` {_num((m.get('validation') or {}).get('sharpe'), '.2f')}" for k, m in bl.items()) + "."]
    return lines


def _link(ref: str) -> str:
    """Absolute link in Actions, so it also works from the results branch; relative otherwise."""
    repo = os.environ.get("GITHUB_REPOSITORY")
    return f"https://github.com/{repo}/blob/main/{ref}" if repo else ref


def section(ledger: Path, broker=None, now: dt.datetime | None = None, fund_brokers: dict | None = None) -> str:
    now = now or dt.datetime.now(dt.timezone.utc)
    champ = json.loads((ROOT / "state" / "champion.json").read_text())
    lines = [RESULTS_START, f"_Updated {now:%Y-%m-%d %H:%M} UTC by `factory/readme.py` from the ledger branch"
             f"{' and the Alpaca paper account' if broker is not None else ''}._", "",
             f"### Current strategy: `{champ.get('name')}`",
             f"- {champ.get('timeframe')} bars, promoted {str(champ.get('promoted_at'))[:10]}, source "
             f"[{champ.get('ref')}]({_link(champ.get('ref', ''))})."]
    if m := methodology(champ.get("ref", "")):
        lines.append(f"- Method: {m}")
    runs = executions(ledger)
    if fund_brokers is None and broker is not None:
        fund_brokers = {1: broker}
    lines += [""] + fund_section(runs, fund_brokers) + [""] + trading_section(runs, broker) + [""]
    lines += research_section(ledger, champ) + [RESULTS_END]
    return "\n".join(lines)


def splice(readme: str, block: str) -> str:
    if RESULTS_START in readme and RESULTS_END in readme:
        head, rest = readme.split(RESULTS_START, 1)
        return head + block + rest.split(RESULTS_END, 1)[1]
    return readme.rstrip("\n") + "\n\n## Results\n" + block + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ledger", required=True)
    ap.add_argument("--readme", default=str(ROOT / "README.md"))
    ap.add_argument("--no-broker", action="store_true")
    a = ap.parse_args(argv)
    path = Path(a.readme)
    brokers = None
    if not a.no_broker:
        brokers = {}
        from factory import funds
        from factory.broker import PaperBroker
        for n in range(1, funds.MAX_FUNDS + 1):
            if creds := funds.credentials(n):
                try:
                    brokers[n] = PaperBroker(*creds)
                except Exception as e:
                    print(f"fund {n} broker unavailable: {e}", file=sys.stderr)
    path.write_text(splice(path.read_text(), section(Path(a.ledger), (brokers or {}).get(1), fund_brokers=brokers)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
